services:
  java:
    build:
      context: .
      dockerfile: Dockerfile
      target: java
    container_name: impactoambiental-java
    ports:
      - 8080:80
    environment:
      - DB_URL=jdbc:postgresql://db:5432/impactoambiental
      - DB_USERNAME=jpademo
      - DB_PASSWORD=jpademo
      - GEODDS_API_KEY=${GEODDS_API_KEY}
      - PORT=80
      - RECOMENDACIONES_TEMPLATE=${RECOMENDACIONES_TEMPLATE}
      - RECOMENDACIONES_URL=${RECOMENDACIONES_URL}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - WEAK_PASSWORDS_FILE=${WEAK_PASSWORDS_FILE}
      - WHATSAPP_API_KEY=${WHATSAPP_API_KEY}
      - WHATSAPP_API_ID=${WHATSAPP_API_ID}
    depends_on:
      - db

  cron:
    build:
      context: .
      dockerfile: Dockerfile
      target: cron
    container_name: impactoambiental-cron
    environment:
      - DB_URL=jdbc:postgresql://db:5432/impactoambiental
      - DB_USERNAME=jpademo
      - DB_PASSWORD=jpademo
      - GEODDS_API_KEY=${GEODDS_API_KEY}
      - RECOMENDACIONES_TEMPLATE=${RECOMENDACIONES_TEMPLATE}
      - RECOMENDACIONES_URL=${RECOMENDACIONES_URL}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - WEAK_PASSWORDS_FILE=classes/weak_passwords.txt
      - WHATSAPP_API_KEY=${WHATSAPP_API_KEY}
      - WHATSAPP_API_ID=${WHATSAPP_API_ID}
    depends_on:
      - db

  db:
    image: postgres:9.3-alpine
    container_name: impactoambiental-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=impactoambiental
      - POSTGRES_USER=jpademo
      - POSTGRES_PASSWORD=jpademo
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: impactoambiental-data
    external: true
