services:
  java:
    build:
      context: .
      dockerfile: Dockerfile
      target: java
      args:
        - DB_URL=${DB_URL:-jdbc:postgresql://db:5432/impactoambiental}
        - DB_USERNAME=${DB_USERNAME:-jpademo}
        - DB_PASSWORD=${DB_PASSWORD:-jpademo}
    container_name: impactoambiental-java
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    environment:
      - GEODDS_API_KEY=${GEODDS_API_KEY}
      - PORT=${PORT:-8080}
      - RECOMENDACIONES_TEMPLATE=${RECOMENDACIONES_TEMPLATE}
      - RECOMENDACIONES_URL=${RECOMENDACIONES_URL:-recomendaciones}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - WEAK_PASSWORDS_FILE=${WEAK_PASSWORDS_FILE:-/app/target/classes/weak_passwords.txt}
      - WHATSAPP_API_KEY=${WHATSAPP_API_KEY}
      - WHATSAPP_API_ID=${WHATSAPP_API_ID}
    depends_on:
      - db

  cron:
    build:
      context: .
      dockerfile: Dockerfile
      target: cron
      args:
        - CRON_ENVIO_GUIA=${CRON_ENVIO_GUIA:-* * * * *}
        - DB_URL=${DB_URL:-jdbc:postgresql://db:5432/impactoambiental}
        - DB_USERNAME=${DB_USERNAME:-jpademo}
        - DB_PASSWORD=${DB_PASSWORD:-jpademo}
    container_name: impactoambiental-cron
    environment:
      - GEODDS_API_KEY=${GEODDS_API_KEY}
      - RECOMENDACIONES_TEMPLATE=${RECOMENDACIONES_TEMPLATE}
      - RECOMENDACIONES_URL=${RECOMENDACIONES_URL:-recomendaciones}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - WEAK_PASSWORDS_FILE=${WEAK_PASSWORDS_FILE:-/app/target/classes/weak_passwords.txt}
      - WHATSAPP_API_KEY=${WHATSAPP_API_KEY}
      - WHATSAPP_API_ID=${WHATSAPP_API_ID}
    depends_on:
      - db

  db:
    image: postgres:9.3-alpine
    container_name: impactoambiental-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=impactoambiental
      - POSTGRES_USER=jpademo
      - POSTGRES_PASSWORD=jpademo
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: impactoambiental-data
    external: true
