services:
#  java:
#    build: .
#    container_name: impactoambiental-java
#    command: impactoambiental-1.0-SNAPSHOT-jar-with-dependencies.jar
#    environment:
#      - GEODDS_API_KEY=${GEODDS_API_KEY:?}
#      - POSTGRES_DB=${POSTGRES_DB:?}
#      - POSTGRES_USER=${POSTGRES_USER:?}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
#      - POSTGRES_SERVICE=db:5432
#      - RECOMENDACIONES_CRON=${RECOMENDACIONES_CRON:?}
#      - RECOMENDACIONES_TEMPLATE=${RECOMENDACIONES_TEMPLATE:?}
#      - RECOMENDACIONES_URL=${RECOMENDACIONES_URL:?}
#      - SMTP_USER=${SMTP_USER:?}
#      - SMTP_PASSWORD=${SMTP_PASSWORD:?}
#      - WHATSAPP_API_KEY=${WHATSAPP_API_KEY:?}
#      - WHATSAPP_ID=${WHATSAPP_ID:?}
#    depends_on:
#      - db

  db:
    image: postgres:9.3-alpine
    container_name: impactoambiental-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=impactoambiental
      - POSTGRES_USER=jpademo
      - POSTGRES_PASSWORD=jpademo
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: impactoambiental-data
    external: true
