services:
  java:
    build:
      context: .
      dockerfile: Dockerfile
      target: java
    container_name: impactoambiental-java
    env_file:
      - .env
    environment:
      - POSTGRES_SERVICE=db:5432
    depends_on:
      - db

  cron:
    build:
      context: .
      dockerfile: Dockerfile
      target: cron
    container_name: impactoambiental-cron
    env_file:
      - .env
    environment:
      - POSTGRES_SERVICE=db:5432
    depends_on:
      - db

  db:
    image: postgres:9.3-alpine
    container_name: impactoambiental-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=impactoambiental
      - POSTGRES_USER=jpademo
      - POSTGRES_PASSWORD=jpademo
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: impactoambiental-data
    external: true
